### ISSUE TITLE
2 problems when using MPB

### ISSUE THREAD

**Issue by leoyhr** [stevengj/mpb#10]
Hi Steven,
Thank u so much for your helpful work firstly.
As a newie to MPB, I get two problems when using MPB:

1.If output the E-field, we have both real and imaginary part, as what is mentioned in MPB DATA ANALYSIS TUTORIAL: "The real and imaginary parts of the fields correspond to what the fields look like at half-period intervals in time" 
  My first question is : why is the imaginary part is the the field after half-period interval compared with real part? Is this a mathematical result(the output of the eigenvector with both real and imaginary part)?     
  I checked the Developer Information and went through the code roughly but didn't get the answer.

2.The second quesion is about the resolution. Becoz I got a problem that if I improve the resolution to a very high level,e.g. set the resolution at 256 for a 2D case, the plot of the efield with 'h5topng' is distorted and strange, very different from those at resolution of 32 or 64.
  So I wonder if there would be something wrong if the resolution is too high from the theory? 

 I do hope these questions are non-trivial, but make me know if they are stupid:)
 Thank you.

Cheers,
Hanrong

**Comment by stevengj** [comment]
On your first question, the physical fields are `Re[E * exp(-iωt)]`, so the result follows.  See e.g. chapter 2 of http://ab-initio.mit.edu/book/

Regarding your second question, I haven't seen this.  Without more details it is impossible to say.

However, note that the the phase of the efield output is arbitrary, so it will vary randomly from run to run unless you use e.g. `fix-efield-phase` as explained in the manual.  This means that when you plot something like the real part, which depends on the phase, it will vary from run to run (and may look strange if the phase happens to be such that the real part is nearly zero).

(In general, you should use the mpb-discuss mailing list for questions like your first question, and you should file a single issue for each problem rather than filing distinct issues.)

**Comment by leoyhr** [comment]
Sorry for that mistake.
So it means that the imaginary part is not REALLY imaginary part, am I right? I just want to make sure.
And for the second question I think you hit the point.
Thanks a lot!

**Comment by leoyhr** [comment]
Sorry for that mistake
Problems solved, thanks a lot!
Leo
