### ISSUE TITLE
Compiling on Fedora21

### ISSUE THREAD

**Issue by hmaarrfk** [stevengj/mpb#4]
Hi Steven,

I was compiling mpb on Fedora 21 and ran into some issues with LIBCTL

I made a few patches I think are easy enough to merge:

Modification to configure.ac so that lib.ctl can be found: (inspired from the patch for MEEP)
https://github.com/hmaarrfk/meep-rpm/blob/master/mpb-Fedoralibctl.patch

Modifications to automake so that ctl.h can be found:
https://github.com/hmaarrfk/meep-rpm/blob/master/mpb-testCTL.patch
https://github.com/hmaarrfk/meep-rpm/blob/master/mpb-utilsCTL.patch

Honestly, I am not an export with automake so I'm note sure If I included the modifications in the correct locations.

Hope it helps

**Comment by hmaarrfk** [comment]
So this effort culminated with the creation of Fedora repositories

https://copr.fedoraproject.org/coprs/hmaarrfk/meep/

For MPI support, you need
https://copr.fedoraproject.org/coprs/hmaarrfk/fftw2-mpi/

for FFTW2 with MPI.

Just wanted to put it out there one way or an other.

**Comment by stevengj** [comment]
You don't need to modify any of the automake files etcetera.   You can specify all of the necessary paths to the configure script with `./configure CPPFLAGS="-I ...." LDFLAGS="-L ..." --with-libctl-dir=/path/to/share/libctl`.

**Comment by hmaarrfk** [comment]
Hi Steven,

I don't have time to test everything right now, but adding adding ```./configure CPPFLAGS="-I/usr/include/ctl``` seems to have worked. 

Thanks.

There seems to be logic in the configure script for finding the alternate CTL paths though. I wonder why it simply gets discarded. The logic in configure.ac starts at lines 392.

I think it makes sense to me to remove line 404 (keeping the required brackets of course) since the useful CPPFLAGS will have been set by the for loop.

https://github.com/hmaarrfk/meep-rpm/blob/master/mpb-configure_ac_libctl.patch

Thanks again for your help.

**Comment by stevengj** [comment]
@hmaarrfk, no, that patch is not correct.   The logic here is that it repeatedly adds something to `CPPFLAGS`, tests it, and then resets `CPPFLAGS`.  If you remove the `CPPFLAGS=$save_CPPFLAGS` line then you will end up adding all the paths that were attempted to `CPPFLAGS`, even if they didn't work.   Instead, if the path is found it is added to `CTL_H_CPPFLAG`, which is used in the `Makefile.am`.

However, the current logic is not right, because it needs to be added to `CPPFLAGS` for the remaining tests in the `configure.ac` file, which were added later.

**Comment by hmaarrfk** [comment]
Line 408:
CPPFLAGS="$save_CPPFLAGS -I$ctl_h_path"
ensures that all the paths are not added.

The way you wrote it makes it more obvious what is going on.

Thanks for the fix.

Mark

**Comment by stevengj** [comment]
Right.
