### ISSUE TITLE
Error during the installation of MPB

### ISSUE THREAD

**Issue by Saranyanarayanan** [stevengj/mpb#47]
While installing mpb-1.6.1 I encountered with the following error:
configure: error: The FFTW libraries could not be found.  Make sure FFTW is installed, and that LDFLAGS and CPPFLAGS are set appropriately if necessary.
I tried with sentenv LDFLAGS "-L/usr/local/lib"
                 sentenv CPPFLAGS "-I/usr/loal/include"
but it is not helping.
I am kind of new with Linux and programming.  
I know you have already answered these types of questions, i tried all those possible ways and still unable to proceed. 
fftw-wisdom tool for FFTW version 3.3.3.

**Comment by stevengj** [comment]
"Permission denied" is because you need to [use the sudo command](https://www.linux.com/blog/how-use-sudo-and-su-commands-linux-introduction) in order to install software in system-wide directories.

(Rather than compiling from source, you should normally install FFTW and other dependencies using the system packages for your Linux distribution.)

Unfortunately, if you are this new to Linux, you are going to have a lot of trouble installing software from source if has as many dependencies as MPB.  I would suggest finding a local Linux guru to help you.

**Comment by Saranyanarayanan** [comment]
Thank you Sir.
